kind: pipeline
name: default

pipeline:
  gcr:
    image: plugins/gcr
    # registry: gcr.io
    settings:
      registry: gcr.io
      repo: pixellate/github.com/dickygeraldi/user_services
      tags: ["commot_${DRONE_COMMIT}", "build_${DRONE_BUILD_NUMBER}", "latest"]
      json_key:
        from_secret: GOOGLE_CREDENTIALS 
    # repo: pixellate/user_services aa1059e5382b1d9a01c7b1660a59fe6a6e8232cc
    # tags: ["commit_${DRONE_COMMIT}", "build_${DRONE_BUILD_NUMBER}", "latest"] sada
    # secrets: [GOOGLE_CREDENTIALS] 936ea74bec13d09fd9b398edac8997a5fbd2ba26
    when: 
      branch: develop
    

  deploy:
    image: Google/cloud-sdk:latest  
    environment:
      PROJECT_ID: pixellate
      COMPUTE_ZONE: asia-southeast1-a
      CLUSTER_NAME: user-services
    secrets: [GOOGLE_CREDENTIALS]
    commands:
      - yes | apt-get install golang-1.12 
      - gcloud config set project $PROJECT_ID
      - gcloud config set compute/zone $COMPUTE_ZONE 
      - gcloud auth activate-service-account --key-file key.json
      - gcloud container clusters get-credentials $CLUSTER_NAME
      - kubectl set image deployment/user-services user-services=gcr.io/$PROJECT_ID/app:$DRONE_BUILD_NUMBER
    when:
      branch: master
