kind: pipeline
name: default

pipeline:
  gcr:
    image: plugins/gcr
    registry: asia.gcr.io
      # registry: asia.gcr.io
      # repo: pixellate/pixellate-user_services
      # tags: ["commot_${DRONE_COMMIT}", "build_${DRONE_BUILD_NUMBER}", "latest"]
      # json_key: aa1059e5382b1d9a01c7b1660a59fe6a6e8232cc
      #   from_secret: GOOGLE_CREDENTIALS  sdads
    repo: pixellate/pixellate-user-services 
    tags: ["commit_${DRONE_COMMIT}", "build_${DRONE_BUILD_NUMBER}", "latest"]
    secrets: [GOOGLE_CREDENTIALS]
    when: 
      branch: develop
    
  deploy:
    image: google/cloud-sdk:latest  
    environment:
      PROJECT_ID: pixellate
      COMPUTE_ZONE: asia-southeast1-a
      CLUSTER_NAME: pixellate-user-service-dev
    secrets: [GOOGLE_CREDENTIALS]
    commands:
      - yes | apt-get install golang-1.12 
      - gcloud config set project $PROJECT_ID
      - gcloud config set compute/zone $COMPUTE_ZONE 
      - gcloud auth activate-service-account --key-file key.json
      - gcloud container clusters get-credentials $CLUSTER_NAME
      - kubectl set image deployment/pixellate-user-services-dev pixellate-user-services-dev=asia.gcr.io/$PROJECT_ID/app:$DRONE_BUILD_NUMBER
    when:
      branch: develop
